### ISSUE TITLE
buildout fails using the system virtualenv on Kubuntu 12.04

### ISSUE THREAD

**Issue by benzolius** [plone/training#141]
When I use virtualenv from the system in order to create the "py27" virtual environment I got the following error from buildout:

While:
  Installing.
  Loading extensions.
  Getting distribution for 'mr.developer==1.33'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/buildout.py", line 507, in install
    self._load_extensions()
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/buildout.py", line 1032, in _load_extensions
    newest=self.newest, allow_hosts=self._allow_hosts)
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 234, in _satisfied
    return None, self._obtain(req, source)
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 420, in _obtain
    if _final_version(dist.parsed_version)
  File "/home/training/buildout/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 1407, in _final_version
    return not parsed_version.is_prerelease
AttributeError: 'tuple' object has no attribute 'is_prerelease' 

I could install it though, by installing an independent virtual environment:

mkdir tmp
wget --no-check-certificate "https://raw.github.com/pypa/virtualenv/master/virtualenv.py" -O "tmp/virtualenv.py"
python tmp/virtualenv.py --clear py27
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | py27/bin/python
wget --no-check-certificate "https://raw.github.com/pypa/pip/master/contrib/get-pip.py" -O "tmp/get-pip.py"
py27/bin/python "tmp/get-pip.py"

./py27/bin/python bootstrap.py
./bin/buildout

I've got errors for some packages, but now Plone is working.

**Comment by do3cc** [comment]
Maybe a pip --upgrade might have made it work with your system pyenv.
All these wheels to make things work are really flaky and there is not much one can do, apart from knowing which pecularity exists this week.
One improvement could be if we provide a requirements.txt file to make sure pip install the right versions of setuptools, before bootstrapping.

**Comment by fulv** [comment]
FWIW, I never use the system python on my local dev machine, but
use collective/buildout.python.

**Comment by benzolius** [comment]
Thanks for ideas. In fact I could solve it, but I wanted to document the issue.

**Comment by jensens** [comment]
outdated
