### ISSUE TITLE
Make build

### ISSUE THREAD

**Issue by tisto** [plone/training#333]
I just tried to build this training for the first time and I somehow expected that "make" would just build everything for me.

Creating a virtualenv and installing the requirements.txt is straightforward. Though, what is the reason for having to install sphinx-build globally?

Maybe we can add a "make build" that is run by default so this becomes a no-brainer for newbies. Optinions?

**Comment by ajayns** [comment]
I'm still a bit confused about the development setup process for this. Is there any docs available or a straightforward script I can just use directly?

**Comment by stevepiercy** [comment]
@pbauer should the Python version be bumped here to 3.7?
https://training.plone.org/5/mastering-plone/about_mastering.html#build-new

Note that if you don't have the latest Python 2.7.15, then you will have a problem installing `sphinxcontrib-spelling` and its dependency `pbr`. macOS 10.12.6 uses an old janky Python 2.7.10, and I forgot to use my 2.7.15 in my pyenv, which led to the error below. Using 2.7.15 worked.

```
Collecting sphinxcontrib-spelling==4.2.0 (from -r requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/74/22/3fc121b8a7acd4952e0a280ced4703ed0082ae61533204731ef4cdfa01cb/sphinxcontrib-spelling-4.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pbr/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for pbr
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fx/p4fx43ts6f1dqgj29c0y20yc0000gn/T/pip-install-3mKAbU/sphinxcontrib-spelling/setup.py", line 14, in <module>
        pbr=True)
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in setup
        _install_setup_requires(attrs)
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/setuptools/__init__.py", line 134, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1060, in best_match
        return self.obtain(req, installer)
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1072, in obtain
        return installer(requirement)
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/stevepiercy/projects/Plone/training/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fx/p4fx43ts6f1dqgj29c0y20yc0000gn/T/pip-install-3mKAbU/sphinxcontrib-spelling/
```

**Comment by stevepiercy** [comment]
@tisto I did not have to install Sphinx globally. Where do you see that in the docs?

**Comment by svx** [comment]
IMHO we could remove sphinx-contrib spelling there are better tools these days, which you can hook up with/including testing against all your style-guides, for example vale or textlint.

Both of them are also way faster.

But for doing so we need the training docs (like the normal docs) to be in a better state :)

Speaking about the install/setup, I guess it depends on your own need/usage ?

I have one container running sphinx, for all of my projects, using that on macOS and linux, so I do not bother anymore with virtualenv for each setup.
If there is an egg missing (like an add-on) I through it into the container, done

Please note, this is my personal opinion, I am not saying we/you have to do that, it is all what fits you best.

**Comment by tisto** [comment]
If we want people to contribute we should make this as easy as running IMHO:

```make```

If a core developer has to look up how this works and needs a pointer, how can we expect a newbie to fix a typo...

**Comment by tisto** [comment]
@svx @pbauer I tried my best to make just typing "make" work for the setup:

https://github.com/plone/training/pull/441

Though, neither Makefiles nor Jenkinsfiles work well with activating virtualenvs in my experience. Therefore we would have to refactor that as well. What do you think?

I just had to set up things manually for two of my colleagues. If we make it that hard to build our docs we can not expect newbies to help us with improving it...this is definitely something that we have to fix.
