### ISSUE TITLE
Errors when following "Installing Plone without vagrant" - conflicting setuptools versions?

### ISSUE THREAD

**Issue by procmail** [plone/training#65]
Are different versions of setuptools needed for python bootstrap.py and bin/buildout?

```
python bootstrap.py
Traceback (most recent call last):
  File "bootstrap.py", line 159, in <module>
    ws.require(requirement)
  File "/Users/eric/.virtualenvs/training2/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/eric/.virtualenvs/training2/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 0.9.8 (/Users/eric/.virtualenvs/training2/lib/python2.7/site-packages), Requirement.parse('setuptools>=8.0'))
```
Do a `pip install -U setuptools`,  then `bin/buildout `

When doing a `bin/buildout`, I get this:
```
bin/buildout
Getting distribution for 'mr.developer==1.21'.
Got mr.developer 1.21.
Getting distribution for 'zc.buildout==1.7.1'.
Got zc.buildout 1.7.1.
Getting distribution for 'setuptools==0.6c11'.
While:
  Installing.
  Loading extensions.
  Getting distribution for 'setuptools==0.6c11'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/eric/.virtualenvs/training2/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/Users/eric/.virtualenvs/training2/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 467, in install
    self._load_extensions()
  File "/Users/eric/.virtualenvs/training2/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 995, in _load_extensions
    newest=self.newest, allow_hosts=self._allow_hosts)
  File "/Users/eric/.virtualenvs/training2/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/Users/eric/.virtualenvs/training2/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 685, in install
    for_buildout_run=for_buildout_run):
  File "/Users/eric/.virtualenvs/training2/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 549, in _get_dist
    dist = self._env.best_match(requirement, ws)
  File "/Users/eric/.virtualenvs/training2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1068, in best_match
    dist = working_set.find(req)
  File "/Users/eric/.virtualenvs/training2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 705, in find
    raise VersionConflict(dist, req)
VersionConflict: (setuptools 15.2 (/Users/eric/.virtualenvs/training2/lib/python2.7/site-packages), Requirement.parse('setuptools==0.6c11'))
```

**Comment by allcaps** [comment]
I encountered the same error and specified the bootstrap an setuptools versions:
`python2.7 bootstrap.py --version=2.2.5 --setuptools-version=7.0`
